version: "2"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - "6379:6379"
  # cassandra:
  #   image: "cassandra:latest"
  #   networks:
  #     - app-tier
  #   ports:
  #     - "7000:7000"
  #     - "7001:7001"
  #     - "7199:7199"
  #     - "9042:9042"
  #     - "9160:9160"
  #     - "9404:9404"
  chat-server:
    build: ./infra/node
    container_name: chat-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    working_dir: /home/node/app
    volumes:
      - ./server:/home/node/app
      - ./server/node_modules:/home/node/app/node_modules
    networks:
      - app-tier
    command: yarn start:dev
    cpus: 2
  chat-front:
    build: ./infra/node
    container_name: chat-front
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    networks:
      - app-tier
    command: yarn start
    stdin_open: true
    tty: true
    cpus: 2
  db:
    image: mysql:5.7.21
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - app-tier
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
